version: 2
jobs:
  build:
    macos:
      xcode: 10.1.0
    steps:
      - checkout
      - run:
          name: Setup keychain
          environment:
            KEYCHAIN_NAME: demo-keychain.keychain
            KEYCHAIN_PASSWORD: demokeychainpassword
          command: |
            security create-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            # Disable keychain locking timeout
            security set-keychain-settings $KEYCHAIN_NAME
            security unlock-keychain -p $KEYCHAIN_PASSWORD $KEYCHAIN_NAME
            security default-keychain -s $KEYCHAIN_NAME
      - run:
          name: Install App Center CLI
          command: |
            npm -g install appcenter-cli
      - run:
          name: Log in to App Center 
          command: |
            appcenter telemetry off --disable-telemetry
            appcenter login --token $APP_CENTER_API_TOKEN --quiet
      - run:
          name: Test using App Center
          command: |
            appcenter logout
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build